// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package vote

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UpvoteServiceClient is the client API for UpvoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpvoteServiceClient interface {
	Upvote(ctx context.Context, in *UpvoteRequest, opts ...grpc.CallOption) (UpvoteService_UpvoteClient, error)
}

type upvoteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUpvoteServiceClient(cc grpc.ClientConnInterface) UpvoteServiceClient {
	return &upvoteServiceClient{cc}
}

func (c *upvoteServiceClient) Upvote(ctx context.Context, in *UpvoteRequest, opts ...grpc.CallOption) (UpvoteService_UpvoteClient, error) {
	stream, err := c.cc.NewStream(ctx, &UpvoteService_ServiceDesc.Streams[0], "/vote.UpvoteService/Upvote", opts...)
	if err != nil {
		return nil, err
	}
	x := &upvoteServiceUpvoteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UpvoteService_UpvoteClient interface {
	Recv() (*UpvoteResponse, error)
	grpc.ClientStream
}

type upvoteServiceUpvoteClient struct {
	grpc.ClientStream
}

func (x *upvoteServiceUpvoteClient) Recv() (*UpvoteResponse, error) {
	m := new(UpvoteResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UpvoteServiceServer is the server API for UpvoteService service.
// All implementations must embed UnimplementedUpvoteServiceServer
// for forward compatibility
type UpvoteServiceServer interface {
	Upvote(*UpvoteRequest, UpvoteService_UpvoteServer) error
	mustEmbedUnimplementedUpvoteServiceServer()
}

// UnimplementedUpvoteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUpvoteServiceServer struct {
}

func (UnimplementedUpvoteServiceServer) Upvote(*UpvoteRequest, UpvoteService_UpvoteServer) error {
	return status.Errorf(codes.Unimplemented, "method Upvote not implemented")
}
func (UnimplementedUpvoteServiceServer) mustEmbedUnimplementedUpvoteServiceServer() {}

// UnsafeUpvoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpvoteServiceServer will
// result in compilation errors.
type UnsafeUpvoteServiceServer interface {
	mustEmbedUnimplementedUpvoteServiceServer()
}

func RegisterUpvoteServiceServer(s grpc.ServiceRegistrar, srv UpvoteServiceServer) {
	s.RegisterService(&UpvoteService_ServiceDesc, srv)
}

func _UpvoteService_Upvote_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UpvoteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UpvoteServiceServer).Upvote(m, &upvoteServiceUpvoteServer{stream})
}

type UpvoteService_UpvoteServer interface {
	Send(*UpvoteResponse) error
	grpc.ServerStream
}

type upvoteServiceUpvoteServer struct {
	grpc.ServerStream
}

func (x *upvoteServiceUpvoteServer) Send(m *UpvoteResponse) error {
	return x.ServerStream.SendMsg(m)
}

// UpvoteService_ServiceDesc is the grpc.ServiceDesc for UpvoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpvoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vote.UpvoteService",
	HandlerType: (*UpvoteServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upvote",
			Handler:       _UpvoteService_Upvote_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc/data.proto",
}
